[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.28" }
annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.21.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
