[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
